broker_auth:
  user: (( param "Please override broker_auth.user" ))
  password: (( param "Please override broker_auth.password" ))
service_name: config-server
service_id: config-server
basic_plan_name: basic
basic_plan_id: basic
description: Broker to create config-servers
long_description: Broker to create config-servers
config_server_release_tag: v3.1.0
cloud_foundry_config:
  api_url: (( param "Please override cloud_foundry_config.api_url in inputs.yml" ))
  skip_ssl_validation: true
  cf_username: (( param "Please override uaa_config.username" ))
  cf_password: (( param "Please override uaa_config.password" ))
  uaa_client_id: (( param "Please override uaa_config.client_id" ))
  uaa_client_secret: (( param "Please override uaa_config.client_secret" ))
instance_space_guid: (( param "Please override instance_space_guid" ))
instance_domain: (( param "Please override instance_domain" ))
